src/main/kotlin/no/digdir/fdk/searchservice/model/Dataset.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/DatasetSearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/ConceptTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/DatasetTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/utils/TestData.kt
=> feat: add search filter for isOpen and accessRights

README.md, src/main/kotlin/no/digdir/fdk/searchservice/config/IndexNames.kt, src/main/kotlin/no/digdir/fdk/searchservice/controller/DataserviceController.kt, src/main/kotlin/no/digdir/fdk/searchservice/elastic/SearchRepositories.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/Dataservice.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/DataserviceSearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/DataserviceTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/utils/ApiTestContext.kt, src/test/kotlin/no/digdir/fdk/searchservice/utils/TestData.kt
resolves https://github.com/Informasjonsforvaltning/fdk-search-service/issues/30
=> feat: refactor elastic search model

src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DatasetTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/DatasetTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/utils/ApiTestContext.kt
=> feat: add filter provenance to datasets

src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DatasetTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
=> feat: add filter spatial to dataset

src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DatasetTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
=> feat: add filter on OrgPath

docker-compose.yaml, kafka/create_topics.sh, kafka/schemas/no.fdk.concept.ConceptEvent.avsc, kafka/schemas/no.fdk.dataservice.DataServiceEvent.avsc, kafka/schemas/no.fdk.dataset.DatasetEvent.avsc, kafka/schemas/no.fdk.event.EventEvent.avsc, kafka/schemas/no.fdk.informationmodels.InformationModelEvent.avsc, kafka/schemas/no.fdk.service.ServiceEvent.avsc, src/main/kotlin/no/digdir/fdk/searchservice/kafka/KafkaRdfParseEventConsumer.kt, src/main/kotlin/no/digdir/fdk/searchservice/kafka/KafkaRemovedEventConsumer.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/CommonMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/DataServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/EventMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/InformationModelMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/ServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/CommonEnumClasses.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/Concept.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/DataService.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/Event.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/InformationModel.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/SearchObject.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/Service.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/ConceptTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DatasetTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/SearchObjectTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/utils/ApiTestContext.kt
Fixes #44 
Fixes #45 
Fixes #46
Fixes #47 
Fixes #48
=> feat: remove search object based on removed message

src/main/kotlin/no/digdir/fdk/searchservice/mapper/DataServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/DataService.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DataServiceTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
=> feat: add format to dataservices

src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/ServiceTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/ConceptTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/DataServiceTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/DatasetTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/EventTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/InformationModelTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/SearchObjectTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/ServiceTest.kt
=> feat: only search in specific fields

src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
=> feat: add sorting on first harvested

src/main/kotlin/no/digdir/fdk/searchservice/model/Pagination.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/SearchResult.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/main/resources/elastic/mapping.json, src/test/kotlin/no/digdir/fdk/searchservice/integration/Aggregations.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
=> add aggregations

src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DataServiceTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DatasetTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/InformationModelTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/SearchObjectTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/ServiceTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
ref https://github.com/Informasjonsforvaltning/fdk-rdf-parser/blob/main/src/fdk_rdf_parser/classes/theme.py#L19
=> fix: type of losPaths is List<String> not String

src/main/kotlin/no/digdir/fdk/searchservice/model/CommonDataClasses.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/ConceptTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DataServiceTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DatasetTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/EventTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/InformationModelTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/SearchObjectTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/ServiceTestData.kt
ref: https://github.com/Informasjonsforvaltning/fdk-rdf-parser/blob/main/src/fdk_rdf_parser/classes/publisher.py#L11
=> fix: use correct id-field for org-objects

pom.xml, src/main/kotlin/no/digdir/fdk/searchservice/configuration/ElasticProperties.kt, src/main/kotlin/no/digdir/fdk/searchservice/controller/SuggestionsController.kt, src/main/kotlin/no/digdir/fdk/searchservice/elastic/ElasticSearchConfig.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/Suggestion.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/SuggestionsResult.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SuggestionService.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/SuggestionTest.kt
Fixes https://github.com/Informasjonsforvaltning/fdk-search-service/issues/122
=> fix: move suggestions to result object

src/main/kotlin/no/digdir/fdk/searchservice/mapper/ServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/Service.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/ServiceTestData.kt
=> fix: use other org-type for services

src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/Aggregations.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/ConceptTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/DataServiceTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/DatasetTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/EventTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/InformationModelTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/Pagination.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/SearchObjectTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/ServiceAndEventTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/ServiceTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/SuggestionTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/utils/TestUtils.kt
=> feat: add uri filter

src/main/kotlin/no/digdir/fdk/searchservice/kafka/KafkaRemovedEventConsumer.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/ConceptMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/DataServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/DatasetMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/EventMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/InformationModelMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/ServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/Dataset.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/SearchObject.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DatasetTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/SearchObjectTestData.kt
=> feat: add isAuthoritative

Dockerfile, deploy/demo/env.yaml, deploy/prod/env.yaml, deploy/staging/env.yaml, docker-compose.yaml, pom.xml, src/main/kotlin/no/digdir/fdk/searchservice/configuration/SecurityConfig.kt, src/main/kotlin/no/digdir/fdk/searchservice/controller/SearchController.kt, src/main/kotlin/no/digdir/fdk/searchservice/controller/SuggestionsController.kt, src/main/resources/application.yaml, src/test/kotlin/no/digdir/fdk/searchservice/utils/ApiTestContext.kt
=> chore: add cors configuration

openapi.yaml
resolves #143 
Legger til OpenAPI-spec for tjenesten.
Beskriver ikke interne endepunkter (som metrics, ping og ready).
Spec'en kan klippes og limes inn her for å få en pretty visning: https://editor-next.swagger.io/
=> chore: add open api spec

pom.xml
=> chore: bump jacoco

src/main/kotlin/no/digdir/fdk/searchservice/mapper/ServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/Service.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/ServiceTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/utils/ApiTestContext.kt
fikser kanskje: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/920
=> fix: typo in Service.hasCompetentAuthority

src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/Aggregations.kt
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/922
=> feat: aggregate missing value for accessRights and orgPath

pom.xml, src/main/kotlin/no/digdir/fdk/searchservice/mapper/DataServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/DatasetMapper.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DataServiceTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/DatasetTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/DataServiceTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/DatasetTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/FilterTest.kt
=> fix: index all formats with unknown type as UNKNOWN

pom.xml
Fixes https://github.com/Informasjonsforvaltning/fdk-team-private/issues/82
=> fix: exclude log4j

src/main/kotlin/no/digdir/fdk/searchservice/kafka/KafkaRemovedEventCircuitBreaker.kt
Metrikker registrerte alle meldinger.
=> fix: only inc deleted metric when actual deleted

Dockerfile, src/main/kotlin/no/digdir/fdk/searchservice/kafka/KafkaRemovedEventCircuitBreaker.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/ConceptMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/DataServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/DatasetMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/EventMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/InformationModelMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/mapper/ServiceMapper.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/Concept.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/SearchObject.kt, src/main/kotlin/no/digdir/fdk/searchservice/model/SearchOperation.kt, src/main/kotlin/no/digdir/fdk/searchservice/service/SearchService.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/ConceptTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/data/SearchObjectTestData.kt, src/test/kotlin/no/digdir/fdk/searchservice/integration/ConceptTest.kt, src/test/kotlin/no/digdir/fdk/searchservice/unit/MappingTest.kt
closes https://github.com/Informasjonsforvaltning/fdk-search-service/issues/186
=> feat: make hiddenTerm and altTerm searchable

src/main/resources/application.yaml
=> fix: rm yaml list from kafka bootstrap-servers property
